"""Agregadas nuevas columnas a Instance

Revision ID: 79236f5dc95f
Revises: c67e8d92b9a9
Create Date: 2026-03-30 13:26:58.681090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79236f5dc95f'
down_revision = 'c67e8d92b9a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_vendor', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('position_vendor', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.drop_column('position_vendor')
        batch_op.drop_column('name_vendor')

    # ### end Alembic commands ###
