"""Agregado campo looker_url a Company

Revision ID: c67e8d92b9a9
Revises: 3cebf4611f44
Create Date: 2026-03-04 12:11:30.704159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c67e8d92b9a9'
down_revision = '3cebf4611f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('looker_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('looker_url')

    op.drop_table('phone_line')
    # ### end Alembic commands ###
